### ISSUE TITLE
NO POWERSHELL

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/partner-center-docs-powershell#100]
Seriously, make this a button.  PowerShell is unacceptable, it means the software is still beta.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36204040-31a1-9f48-16d8-a8bae37d222c
* Version Independent ID: a00d5b47-5684-d8fd-a92f-3395989031b1
* Content: [Testing the Partner Security Requirements](https://docs.microsoft.com/en-us/powershell/partnercenter/test-partner-security-requirements?view=partnercenterps-3.0#feedback)
* Content Source: [docs-conceptual/partnercenterps-3.0/test-partner-security-requirements.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/test-partner-security-requirements.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by VNJoe** [comment]
I ran the command in PowerShell and got:

Windows PowerShell
Copyright (C) 2015 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> Test-PartnerSecurityRequirement
Test-PartnerSecurityRequirement : The term 'Test-PartnerSecurityRequirement'
is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ Test-PartnerSecurityRequirement
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Test-PartnerSecurityRequirement
   :String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by isaiahwilliams** [comment]
@VNJoe you will need to install the Partner Center PowerShell module to invoke this command. You can do this by running the following PowerShell command 

```powershell
Install-Module PartnerCenter
```

You can find additional information [here](https://docs.microsoft.com/powershell/partnercenter/install)

**Comment by VNJoe** [comment]
Thanks for the additional information (that should just be above but isn't)!

Since no admin can be without MFA and you can't run these commands unless your admin, THIS SHOULD BE UNIFIED AND UPDATED ACCORDINGLY...

Joe Cimino
CTO, VitalNetix
267 282-5400

________________________________

**Comment by isaiahwilliams** [comment]
@VNJoe this particular command is looking to make sure the expected MFA claim is in the refresh token. If that is missing the test will fail; otherwise, it is successful. Depending on how you have enforced multi-factor authentication the expected claim might not be present. This is typically an issue when you are using federation. 

When you run this command it can be done with any user. It is not dependent on administrative user. You are correct that the partner security requirements state all user accounts in your partner require multi-factor authentication. The purpose of this command it is to validate the configurations you have performed for any user account has been done successfully based on how Microsoft will check if the authentication attempt was challenged for multi-factor authentication.

**Comment by VNJoe** [comment]
I think I understand what you're saying, but the page I came is still unclear:

https://docs.microsoft.com/en-us/partner-center/partner-security-requirements

There's ZERO reason this can't be a button in the portal to run this command if you've logged in there as there's no parameters.

Joe Cimino
CTO, VitalNetix
267 282-5400

________________________________

**Comment by VNJoe** [comment]
When I go to install PartnerCenter, I’m told it’s from an untrusted repository.  Is this accurate?  Seems it should be trusted, especially considering what it’s supposed to do?

**Comment by VNJoe** [comment]
I installed it and restarted my Windows 8.1 machine and now it won't boot.

Awesome. I guess the repository shouldn't have been trusted after all.

Joe Cimino
CTO, VitalNetix
267 282-5400

________________________________
From: Joe Cimino
Sent: Wednesday, January 29, 2020 8:01:22 PM
To: MicrosoftDocs/partner-center-docs-powershell <reply@reply.github.com>
Subject: RE: [MicrosoftDocs/partner-center-docs-powershell] NO POWERSHELL (#100)


When I go to install PartnerCenter, I’m told it’s from an untrusted repository.  Is this accurate?  Seems it should be trusted, especially considering what it’s supposed to do?

**Comment by isaiahwilliams** [comment]
Installing the module should not have resulted in this behavior. I would recommend connecting with Microsoft support if you are still having issues with your computer not booting.
