### ISSUE TITLE
Why is it untrusted?

### ISSUE THREAD

**Issue by VNJoe** [MicrosoftDocs/partner-center-docs-powershell#101]
If we NEED this to ensure things are working properly, shouldn't it be a trusted repository?  Aren't you circumventing the security necessary to protect us?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a17241e-513a-3438-b782-be5a7fa53a05
* Version Independent ID: 0cb11757-bbee-e154-18f4-d36cf0b47a5d
* Content: [Install Partner Center PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/partnercenter/install?view=partnercenterps-3.0)
* Content Source: [docs-conceptual/partnercenterps-3.0/install.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/install.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@VNJoe a default instance of PowerShell does not trust any repository used for installing modules. When you run the command to install a module for the first time it will receive the prompt you have encountered. This is the default behavior and I can confirm that installing this module through the PowerShell gallery is secure. I hope that this helps provide some insight.
