### ISSUE TITLE
Update documentation to say it works for Azure Plan

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-docs-powershell#103]
Please mention Azure Plan somewhere inside this documentation. "Creates a new Azure subscription for Microsoft Partner Agreement billing account." did not make me think of Azure Plan.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6719f8c-c979-687b-7353-1cd05f97bf36
* Version Independent ID: d1bbdb4c-a690-19a1-fc77-bc6d18a59e8e
* Content: [New-PartnerAzureSubscription (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partnerazuresubscription?view=partnercenterps-3.0)
* Content Source: [docs/help/New-PartnerAzureSubscription.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/New-PartnerAzureSubscription.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@o-l-a-v thank you for this feedback, this will be incorporated through an updated that will be made this week.
