### ISSUE TITLE
EXO "CustomerId" - is this tenant ID or can it be tenant's .onmicrosoft.com domain?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/partner-center-docs-powershell#104]
Hello, just wondering if CustomerId has to be the tenant ID, like I could get from Get-AzureADTenantDetail, or can it be the customer.onmicrosoft.com domain?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b50142d-5f12-052b-f0df-884b98fea713
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0#exchange-online-powershell%C2%A0)
* Content Source: [docs-conceptual/partnercenterps-2.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-2.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@JeremyTBradshaw in most circumstances those values are interchangeable. With respect to authentication you will be able to use either value.

**Comment by JeremyTBradshaw** [comment]
@isaiahwilliams Thank you for the answer.
