### ISSUE TITLE
[Q] Possible to revoke previous refresh tokens, if so how?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-docs-powershell#106]
I'm looking for cmdlets to revoke previous refresh tokens. According to some of your documentation (https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#refresh-tokens) refresh tokens should be revoked when you've issued a new one.

* Is this handled automatically? / Are previous refresh token(s) removed when the same app and consented user asks for a new one?
  * For instance when using a refresh token to get a new access and refresh token.
* Can this be done (revoke refresh token) with any existing PartnerCenter module command?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181956ca-ae6d-8e53-4538-494ba0ef4422
* Version Independent ID: 7846349e-7dfe-99cd-67e5-617493f03f0a
* Content: [New-PartnerAccessToken (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partneraccesstoken?view=partnercenterps-3.0)
* Content Source: [docs/help/New-PartnerAccessToken.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/New-PartnerAccessToken.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@o-l-a-v it is possible to revoke all refresh token for a specific user. This action is performed using the [Revoke-AzureAdUserAllRefreshToken](https://docs.microsoft.com/powershell/module/azuread/revoke-azureaduserallrefreshtoken) command from the Azure AD PowerShell module.

**Comment by o-l-a-v** [comment]
@isaiahwilliams 

Thanks, but thats not exactly what I'm looking for.

We have automation for keeping a refresh token valid in a Automation Account. What I'd like is a way of removing all previous issued refresh tokens once I've successfully obtained a new one.

With that Azure AD command that would not be possible, as I'd need user interference for getting a new refresh token again. Right?

**Comment by isaiahwilliams** [comment]
@o-l-a-v that is correct, I am not sure if there is a way to revoke refresh tokens based on a point in time.

**Comment by o-l-a-v** [comment]
@isaiahwilliams 

Ok, so all refresh tokens created thats newer than 14 (how long are they valid by default?) days will still be valid, unless running that AzureAD command?

Hmm. Maybe I shouldn't refresh the tokens as frequent as I do now.

**Comment by isaiahwilliams** [comment]
@o-l-a-v to my knowledge you can only revoke all refresh tokens. You can leverage token policies to make the lifetime shorted. However, since the refresh token is valid for 90 days you can leverage that for a fairly long time.
