### ISSUE TITLE
Data no longer being returned

### ISSUE THREAD

**Issue by jschleicher-work** [MicrosoftDocs/partner-center-docs-powershell#107]
I've automated ETL processes that pull from this source, which has worked fine over the past 6 months.  Today, it's no longer handing data back; no error, just blank response.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff47acf8-6cc0-cc3f-b7e7-4a2995dbc7e4
* Version Independent ID: fd6bda25-3a2e-e454-9c80-a0607d94b800
* Content: [Get-PartnerCustomerSubscriptionUsage (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnercustomersubscriptionusage?view=partnercenterps-1.5#feedback)
* Content Source: [docs/help/Get-PartnerCustomerSubscriptionUsage.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/Get-PartnerCustomerSubscriptionUsage.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
If you run the command with the Debug parameter specified you will be able to see the response from the API. Since there is not an error being thrown I believe this has to deal with the information being returned from the API. 

If this is correct and data is expected, then you might need to open a support ticket through Partner Center. That way the support organization can investigate.

**Comment by jschleicher-work** [comment]
Thanks, Isaiah, for pointing me in the right direction.  Debug response only confirms the authentication details, and throws nothing else back, so I'll run that through Partner Center support.  Thanks, kindly for the fast response!

**Comment by jschleicher-work** [comment]
For posterity, I believe this issue is related to the 18th being our billing cycle rollover date, and so the data is blank because it hasn't been fully generated yet.  That's the working theory, but we'll see what tomorrow brings.  :)
