### ISSUE TITLE
How do you use this sort of authentication in automation?

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/partner-center-docs-powershell#108]
Hello,

If refresh token expires every 90 days how do you do any sort of automation which requires longevity of more then 90 days since it requires manual revalidation at that point? Say I want to run monthly reports on customers from partner center in automated manner, does it mean that every 90 days I have to do some manual steps to make it run successfully?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958c342f-ff57-a57b-9426-8b1bbc9460b2
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0)
* Content Source: [docs-conceptual/partnercenterps-3.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@artisticcheese every time you exchange a refresh token for an access token a new refresh token is returned as well. Which means you can have a process that updates the securely stored refresh token on a specific interval. Some partners are updating their refresh token every week/month, but as long as you do it within 90 days you can avoid performing an interactive login.
