### ISSUE TITLE
"Get-PartnerCustomerUser" with "-ReturnDeletedUsers:$false" returns 0 for some customers

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-docs-powershell#112]
"Get-PartnerCustomerUser" with "-ReturnDeletedUsers:$false" returns 0 for some customers.
I'm sure the customer in question has users that is not deleted, and it works for 7 out of 11 customers.

I'm specifying "-ReturnDeletedUsers:$false" because I like having available parameters visible in scripts no matter if I use them or not. Easier for troubleshooting later on.

PartnerCenter module version: 3.0.7

Reproduce

```powershell
PS C:\Users\OlavRønnestadBirkela&gt; 
# Without -ReturnDeletedUsers:$false
$Users = Get-PartnerCustomerUser -CustomerId $CustomerId;$Users.'Count'
$Users | Group-Object -Property 'State' -NoElement
518

Count Name                     
----- ----                     
  518 Active                   



PS C:\Users\OlavRønnestadBirkela&gt; 
# With -ReturnDeletedUsers:$false
$Users = Get-PartnerCustomerUser -CustomerId $CustomerId -ReturnDeletedUsers:$false;$Users.'Count'
$Users | Group-Object -Property 'State' -NoElement
0

PS C:\Users\OlavRønnestadBirkela&gt; 
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22049c14-255f-883c-0a00-2fadeb7f9bd7
* Version Independent ID: f5960a56-a7bc-c039-3cdb-ab4c4c159d0e
* Content: [Get-PartnerCustomerUser (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnercustomeruser?view=partnercenterps-3.0)
* Content Source: [docs/help/Get-PartnerCustomerUser.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/Get-PartnerCustomerUser.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@o-l-a-v this is due to an issue with the logic used to determine if the list of deleted users should be obtained. Right now if you use the parameter `ReturnDeletedUsers` regardless of whether it is true or false will always attempt to list the deleted users. This is an issue that needs to be corrected, and it should be resolved with the next release.

**Comment by isaiahwilliams** [comment]
Closing this documentation issue because we are tracking the issue as bug [#290](https://github.com/microsoft/Partner-Center-PowerShell/issues/290)
