### ISSUE TITLE
missing parenthesis

### ISSUE THREAD

**Issue by krysstof** [MicrosoftDocs/partner-center-docs-powershell#114]
Hello

the date parameters using the System.dateTimeOffset needs to be in parenthesis to work in both example like this
… -StartDate ([System.DateTimeOffset]::Now.AddDays(-1)) -EndDate ([System.DateTimeOffset]::Now)

otherwise you get a string type conversion error.

I'm using PowerShell on a Windows 10 multilingual (french, with US regional setting, that may be the issue for this)
PS : 5.1  18362  628

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b1c1244-0840-2c42-ac31-7cd03ab68a6a
* Version Independent ID: aa780721-18fa-c6db-518e-a40d502ca1af
* Content: [Get-PartnerCustomerSubscriptionUtilization (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/get-partnercustomersubscriptionutilization?view=partnercenterps-3.0)
* Content Source: [docs/help/Get-PartnerCustomerSubscriptionUtilization.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/Get-PartnerCustomerSubscriptionUtilization.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@krysstof thank you for sharing this information with us. I believe that you are correct, the localization settings you have configured are the reason for the error. We will update this article with the next round of updates to ensure that other do not encounter this issue.

**Comment by isaiahwilliams** [comment]
We will be publishing an update later today that includes this change. Thank you for reporting it.
