### ISSUE TITLE
How do I get child subscriptionID via this module?

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/partner-center-docs-powershell#115]
Hello,

How do I get real subscription ID for a customer by using PartnerCenter module? I can get parent subscriptionID but I do not see which cmdlet would return me child subsription IDs

![image](https://user-images.githubusercontent.com/13176884/78582053-592ef380-77fa-11ea-801e-5c882d71d648.png)

**Comment by isaiahwilliams** [comment]
@artisticcheese you will need to leverage the [Get-PartnerCustomerAzurePlanEntitlement](https://docs.microsoft.com/powershell/module/partnercenter/Get-PartnerCustomerAzurePlanEntitlement) command. When you are using an Azure Plan the subscriptions under the plan are considered entitlements.

**Comment by artisticcheese** [comment]
How do I differentiate between subscriptions for other customers where I get access to actual subscription vs this setup where there is parent and child subscriptions?

**Comment by isaiahwilliams** [comment]
When you run the command you will be specifying the customer identifier. So, the information returned will be scoped to the customer that you specified. Since you are provisioning Azure Plans there will always be the concept of child and parent.

**Comment by artisticcheese** [comment]
My current code get all Subscriptions for partner like `Get-PartnerCustomerSubscription -CustomerId $partner.CustomerId | where OfferName -in @("Azure plan", "Microsoft Azure")`
So if match is on `Azure Plan`  then I need to use `Entitlement` cmdlet but otherwise I can use subscription ID returned directly, right?
