### ISSUE TITLE
Example with EXO v2 Connect-ExchangeOnline

### ISSUE THREAD

**Issue by christianarg** [MicrosoftDocs/partner-center-docs-powershell#116]
Hi,

One of the samples connects to exchange online use the older command New-PSSession

Here https://docs.microsoft.com/en-us/powershell/exchange/exchange-online/exchange-online-powershell-v2/exchange-online-powershell-v2?view=exchange-ps it shows that this is the older command and the newer more efficient (rest, performance, etc) should be done with Connect-ExchangeOnline

Could you add an example with Connect-ExchangeOnline please?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958c342f-ff57-a57b-9426-8b1bbc9460b2
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0)
* Content Source: [docs-conceptual/partnercenterps-3.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@christianarg currently there is not connect to the new Exchange Online module using an access token. Once the [Connect-ExchangeOnline](https://docs.microsoft.com/powershell/module/exchange/powershell-v2-module/connect-exchangeonline) command has the ability to accept an access token for authentication we will be able to include an example.

**Comment by christianarg** [comment]
Rolf. Ok thx

**Comment by christianarg** [comment]
@isaiahwilliams any update on this? Now Microsoft is officialy stating that the older V1 module will be retired https://docs.microsoft.com/en-us/powershell/exchange/v1-module-mfa-connect-to-exo-powershell?view=exchange-ps
