### ISSUE TITLE
Minimal permission for Service Principal

### ISSUE THREAD

**Issue by rdudyk** [MicrosoftDocs/partner-center-docs-powershell#117]
Which permission should has Service Principal to connect to partner center and use "Get-PartnerRoleMember" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41acb5f6-6237-dea0-b508-fdcc31abf897
* Version Independent ID: e467190d-27c2-20bc-3ecc-eee51e377fd0
* Content: [Sign in with Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/authenticate?view=partnercenterps-3.0#feedback)
* Content Source: [docs-conceptual/partnercenterps-3.0/authenticate.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/authenticate.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
Since this is leveraging the Partner Center API the service principal should have the Partner Center permissions configured. However, I do not believe that this operation support app only authentication. So, it is recommended that you leverage app + user authentication. I hope that this helps.
