### ISSUE TITLE
Create-AzureADApplication.ps1 script issue as it relates to Partner Center module v3 and up.

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/partner-center-docs-powershell#128]
The sample script misses adding the necessary 'Microsoft Graph' API Delegated permission 'Directory.AccessAsUser.All'.  The permission is added already by the script sample, but only for the 'Azure Active Directory Graph' API.

You can see this issue discussed over here: https://www.microsoftpartnercommunity.com/t5/Secure-Application-Model/Secure-Application-Model-and-AzureRM/m-p/23103#M194

With the created application as-is, when trying to get an access token for the scope 'https://management.azure.com/user_impersonation', it will fail and require pre-consent which is impossible until this Microsoft Graph API permission is added.  People who have used the script are getting around the issue by manually adding that API permission.

I see in another issue that the script sample has been left un-updated in favor of a future-release of the module where a cmdlet will do the App Registration creation automatically.  If that is also why this fix isn't added, that's OK.  If so, hopefully people who are stuck troubleshooting now will see this info in this GitHub issue.  And also in that case, feel free to just close this issue.  Otherwise, it would be great to have the sample script updated to just add this permission.  It should hurt the v1.5 module in anyway.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2ecd38-7014-b642-4940-86010a7bf26a
* Version Independent ID: dca9cd31-0316-d0aa-949f-a8533c36d5cd
* Content: [Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5)
* Content Source: [docs-conceptual/partnercenterps-1.5/secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/master/docs-conceptual/partnercenterps-1.5/secure-app-model.md)
* Service: **partner-dashboard**
* Sub-service: **partnercenter-sdk**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
Thank you for taking the time to provide this feedback. Currently there are not any plans to add a command to create the Azure AD application registration. However, that is a promising idea and something that can be done. Over the next few weeks I will see what makes the most sense as planning for the next update is under way
