### ISSUE TITLE
Unable query InvoiceLineItems via PowerShell

### ISSUE THREAD

**Issue by mwgroenewald** [MicrosoftDocs/partner-center-docs-powershell#135]
Using the PowerShell module for PartnerCenter (3.0.10), I'm unable to query invoice line line Items.

Error detail below when running Get-PartnerInvoiceLineItem
![image](https://user-images.githubusercontent.com/22740744/97277689-78967800-1841-11eb-97d4-59c381e7ba51.png)

[InvoiceErrors.txt](https://github.com/MicrosoftDocs/partner-center-docs-powershell/files/5443986/InvoiceErrors.txt)

Running "Get-PartnerInvoice" on the other hand works without issues.

**Comment by isaiahwilliams** [comment]
@mwgroenewald thank you for reporting this issue. If you are still encountering this error please open a [bug](https://github.com/microsoft/Partner-Center-PowerShell/issues/new/choose). With this information we should be able to troubleshoot accordingly.
