### ISSUE TITLE
Setting Azure AD Application Reply URL

### ISSUE THREAD

**Issue by ssugar** [MicrosoftDocs/partner-center-docs-powershell#24]
The Reply URL field is only accepting valid URLs and is throwing an error when I try to save urn:ietf:wg:oauth:2.0:oob as a Reply URL.  What's the correct way to configure this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3c68a94-87fb-43a6-023b-127f08e469c9
* Version Independent ID: 7846349e-7dfe-99cd-67e5-617493f03f0a
* Content: [New-PartnerAccessToken (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/New-PartnerAccessToken?view=partnercenterps-1.5)
* Content Source: [docs/help/New-PartnerAccessToken.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/New-PartnerAccessToken.md)
* Service: **partnercenter**
* GitHub Login: @iswillia
* Microsoft Alias: **iswillia**

**Comment by Crazyabout** [comment]
Did you already found out how you can add the urn:ietf:wg:oauth:2.0:oob as a reply URL.
I am really stuck at accessing the refresh token. Can't seem to see where the issue is.

**Comment by Crazyabout** [comment]
You can add it as public client type or see the suggested URL's where the  urn:ietf:wg:oauth:2.0:oob is already provided 
![image](https://user-images.githubusercontent.com/45975657/51396040-88e2d480-1b3e-11e9-8224-093571e224a2.png)

**Comment by isaiahwilliams** [comment]
Hi @ssugar, 

We have just released a new version of the module and updated this documentation. This operation can be accomplished using the Azure portal as @Crazyabout shared or you can use PowerShell to set the property. An example of how to use PowerShell can be found below 

```powershell
Set-AzureADApplication -ObjectId '<Object-Id-Of-Your-App>' -ReplyUrls @("urn:ietf:wg:oauth:2.0:oob")
```
