### ISSUE TITLE
Accessing Partner Central Consent Url doesn't match the URl configured for the application

### ISSUE THREAD

**Issue by Crazyabout** [MicrosoftDocs/partner-center-docs-powershell#25]
I am trying to retrieve the billing data from the Partner Central through API call 

But firstly i'll need some kind of a access_token

From the documentation I got that with executing following Powershell code

        $credential = Get-Credential
    $token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -ServicePrincipal

I will get a refresh token and can execute this Powershell code to retrieve the Token

    $refreshToken = 'Enter the refresh token value here'
    
    $credential = Get-Credential
    $pcToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -Credential $credential -ServicePrincipal
    
    Connect-PartnerCenter -AccessToken $pcToken.AccessToken -AccessTokenExpiresOn $pcToken.ExpiresOn -ApplicationId $appId

But I can't seem to retrieve the refresh token (first PS commands). When i execute the code I'll get Get-Credential login screen where I fill in my Client_ID and Client_secret. Afterwords I'll get a azure login page where I fill in my Credentials.
But I keep to get this error: 
[![enter image description here][1]][1]

Even when I add the URL "https://api.partnercenter.microsoft.com/" in my Azure AD application settings, in the setting redirect URL's:
[![enter image description here][2]][2]

Is there some kind of permission I forgot to give to access the token ?
Or do I miss an obvious step  ?

  [1]: https://i.stack.imgur.com/EL37A.png
  [2]: https://i.stack.imgur.com/VPUwc.png

**Comment by Agazoth** [comment]
I had the same issue until i configured:
![image](https://user-images.githubusercontent.com/15127301/51894512-36a87b80-23a8-11e9-923d-05bbd6735366.png)

as stated here: https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

> To this you will need an Azure AD application that has urn:ietf:wg:oauth:2.0:oob configured as on the reply URLs. The following PowerShell script can be used to create and configure the required Azure AD application

**Comment by isaiahwilliams** [comment]
Hi @Crazyabout, 

Thank you for opening this issue. We have included instructions on how to perform this configuration using PowerShell in the latest update. Please let us know if you have any feedback.

**Comment by Crazyabout** [comment]
@Agazoth  Thnx that did the trick
