### ISSUE TITLE
TenantId missing in example

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/partner-center-docs-powershell#26]
Connect-PartnerCenter -AccessToken $pcToken.AccessToken -AccessTokenExpiresOn $pcToken.ExpiresOn -ApplicationId $appId
Requires the TenantId parameter. It should be:
$TenantId = &lt;Your Tenant Id&gt;
Connect-PartnerCenter -AccessToken $pcToken.AccessToken -AccessTokenExpiresOn $pcToken.ExpiresOn -ApplicationId $appId -TenantId $TenantId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2ecd38-7014-b642-4940-86010a7bf26a
* Version Independent ID: dca9cd31-0316-d0aa-949f-a8533c36d5cd
* Content: [Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5)
* Content Source: [docs-conceptual/partnercenterps-1.5/secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/secure-app-model.md)
* Service: **partner-center**
* GitHub Login: @iswillia
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

Thank you for bring this to my attention. I am getting ready to push a new version of the module out. I will be sure to get this updated when we push out the updated documentation.

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

We have released a new version of the module and updated this documentation. Thank you for bringing this to our attention.
