### ISSUE TITLE
Connect-PartnerCenter -AccessToken not working

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/partner-center-docs-powershell#30]
```Powershell
Connect-PartnerCenter -AccessToken $pcToken.AccessToken -ApplicationId $appId -TenantId $tenantId
Connect-PartnerCenter : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ Connect-PartnerCenter -AccessToken $pcToken.AccessToken -ApplicationI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Connect-PartnerCenter], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Store.PartnerCenter.PowerShell.Commands.ConnectPartnerCenter

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     1.5.1902.2 PartnerCenter                       {Add-PartnerCustomerCartLineItem, Add-PartnerCustomerUserR...
```

**Comment by Crazyabout** [comment]
My guess is that you missed a couple of parameters to provide , the powershell get-help menu gives me this. 
![image](https://user-images.githubusercontent.com/45975657/52423557-a3ceb600-2af8-11e9-8197-3de7cf686570.png)


*PS: not a powershell genius or experienced in partner center. Currently working at  building a script with Partner center myself and I thought maybe this could help you out ;)

**Comment by Agazoth** [comment]
If I run the same command but leave out the -TenantId switch, the command runs as expected

**Comment by isaiahwilliams** [comment]
Hi @Agazoth, 

I have rewritten the documentation for the `Connect-PartnerCenter` command and multiple changes are being merged to address the error you received when using the `TenantId` parameter. The documentation in this repository will be updated when we release the next version. Right now the plan is to have 1.5.1902.3 available early next week.

**Comment by isaiahwilliams** [comment]
All the known issues with this have been resolved.
