### ISSUE TITLE
How does this relate to customer resources

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftDocs/partner-center-docs-powershell#32]
This cmdlet retrieves all cost items, but how can I relate the entries to the actual resources in the customer tenant?

---
#### Dokumentoplysninger

⚠ *Undlad at redigere denne sektion. Det er påkrævet til docs.microsoft.com ➟ GitHub-problemlinkning.*

* ID: 508314f7-990f-1ae0-c41f-07169fd6ef60
* Version Independent ID: af5cb53d-ac9a-7e79-291f-d03582feb949
* Content: [Get-PartnerCustomerServiceCosts (PartnerCenter)](https://docs.microsoft.com/da-dk/powershell/module/partnercenter/Get-PartnerCustomerServiceCosts?view=partnercenterps-1.5)
* Content Source: [docs/help/Get-PartnerCustomerServiceCosts.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/Get-PartnerCustomerServiceCosts.md)
* Service: **partnercenter**
* GitHub Login: @iswillia
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@Agazoth the command only returns information for the customer you specify using the `CustomerId` parameter.. Are you getting information back that is not expected?

**Comment by isaiahwilliams** [comment]
If there are any additional issues please let us know.
