### ISSUE TITLE
Secure Application Model for Exchange Online PowerShell - Possible? If, how?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-docs-powershell#41]
Is it currently possible to use the Secure Application Model with Exchange Online PowerShell? 
* If it is possible, do you have any examples?
* If not possible, is this coming any time soon?

After we implemented the new security requirements for CSP, there is currenly no way AFAIK for us to create Automation Account runbooks using the Exchange Online PowerShell module.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0cdc6d30-fa74-f007-682c-e9c91598adb0
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Multi-factor Authentication](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-1.5)
* Content Source: [docs-conceptual/partnercenterps-1.5/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@o-l-a-v this is currently not possible. I have updated the documentation to include a note about this. There are numerous teams within Microsoft that are working to address this limitation. I hope to have an update on this in the coming days.

**Comment by ivanfioravanti** [comment]
Any feedback on Exchange support? This is needed to use Secure Application Model. Thanks

**Comment by isaiahwilliams** [comment]
@o-l-a-v and @ivanfioravanti we have published information about a [workaround](https://docs.microsoft.com/partner-center/partner-security-requirements#exchange-online-powershell) for this limitation. I would recommend using this workaround, until the limitation has been addressed. Once this has been addressed details will be shared through the [Microsoft Partner Community](https://www.microsoftpartnercommunity.com/t5/Partner-Center-Security-Guidance/ct-p/partner-center-security-guidance).

**Comment by o-l-a-v** [comment]
> @o-l-a-v and @ivanfioravanti we have published information about a [workaround](https://docs.microsoft.com/partner-center/partner-security-requirements#exchange-online-powershell) for this limitation. I would recommend using this workaround, until the limitation has been addressed. Once this has been addressed details will be shared through the [Microsoft Partner Community](https://www.microsoftpartnercommunity.com/t5/Partner-Center-Security-Guidance/ct-p/partner-center-security-guidance).

"You can work around this limitation by creating a new account and never using it to perform an interactive authentication."
How does this comply with CSP requirements for security / MFA? Because you can actually authenticate with this user "interactively", as it's just a regular Azure AD user?
