### ISSUE TITLE
New-PartnerAccessToken requires TenantId

### ISSUE THREAD

**Issue by andrew951** [MicrosoftDocs/partner-center-docs-powershell#43]
`New-PartnerAccessToken` requires a TenantId parameter, but it is not listed in the examples. Please update the documentation to reflect this. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2ecd38-7014-b642-4940-86010a7bf26a
* Version Independent ID: dca9cd31-0316-d0aa-949f-a8533c36d5cd
* Content: [Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5#feedback)
* Content Source: [docs-conceptual/partnercenterps-1.5/secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/secure-app-model.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@andrew951 thank you bringing this to my attention. There is an update for the documentation that is being published right now. This update includes this correction. I really appreciate you taking the time to open this issue.
