### ISSUE TITLE
Connect-MsolService | New-PartnerAccessToken: Supply Value "TenantId" & $appID variable never declared.

### ISSUE THREAD

**Issue by clemans** [MicrosoftDocs/partner-center-docs-powershell#48]
1. TenantId parameters have yet to be updated after multiple reports.

2. The variable **_$appId_** was never declared under the section: **Using the Refresh Token**. 

After hard-coding $appId with the ApplicationId output from the script in section: **Azure AD Application**:

```
Connect-PartnerCenter : Unauthorized access
At line:1 char:1
+ Connect-PartnerCenter -AccessToken $pcToken.AccessToken -ApplicationI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PartnerCenter], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.PowerShell.Commands.ConnectPart
   nerCenter
```

3. After attempting the steps outlined in the section: **MSOnline**

```
Connect-MsolService : An unexpected error occurred.
At line:1 char:1
+ Connect-MsolService -AdGraphAccessToken $aadGraphToken.AccessToken -M ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Connect-MsolService], MicrosoftOnlineException
    + FullyQualifiedErrorId : Microsoft.Online.Administration.Automation.InvalidHeaderException,Microsoft.Online.Administration.Automation.ConnectMso
   lService

Connect-MsolService : Exception of type 'Microsoft.Online.Administration.Automation.MicrosoftOnlineException' was thrown.
At line:1 char:1
+ Connect-MsolService -AdGraphAccessToken $aadGraphToken.AccessToken -M ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Connect-MsolService], MicrosoftOnlineException
    + FullyQualifiedErrorId : Microsoft.Online.Administration.Automation.MicrosoftOnlineException,Microsoft.Online.Administration.Automation.ConnectM
   solService
```

Any help is appreciated. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2ecd38-7014-b642-4940-86010a7bf26a
* Version Independent ID: dca9cd31-0316-d0aa-949f-a8533c36d5cd
* Content: [Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5#feedback)
* Content Source: [docs-conceptual/partnercenterps-1.5/secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/secure-app-model.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by thethird1978** [comment]
I keep getting the same thing.  Been working on this off and on all week.  I finally got the Connect-MsolService command working with access tokens, but no matter what I try with the Connect-PartnerCenter I always get the "Unauthorized Access" error.

Connect-PartnerCenter : Unauthorized access
At line:1 char:1
+ Connect-PartnerCenter -AccessToken $partnerCenterToken.AccessToken -A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-PartnerCenter], PartnerException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.Exceptions.PartnerException,Microsoft.Store.PartnerCenter.
   PowerShell.Commands.ConnectPartnerCenter

**Comment by jonwbstr** [comment]
Well, I created a new app and didn't have any issues connecting to the partner center with the new app either. Open a service ticket, the problem isn't the instructions

**Comment by thethird1978** [comment]
Followed instructions here: https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5 and created a brand new app using the sample powershell code.

Still getting "Connect-PartnerCenter : Unauthorized access" with new application.

**Comment by isaiahwilliams** [comment]
@thethird1978 we have recently release version 2.0 of the module and there a number of breaking changes. Can you update to the latest and try again? 

You can find the updated documentation [here](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0)
