### ISSUE TITLE
Using the Refresh Token...

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/partner-center-docs-powershell#53]
New-PartnerAccessToken requires the -TenantId parameter
```
$credential = Get-Credential
$pcToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -Credential $credential
$tenantId = '&lt;Your Tenant Id&gt;'
```
should be:
```
$credential = Get-Credential
$tenantId = '&lt;Your Tenant Id&gt;'
$pcToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://api.partnercenter.microsoft.com -Credential $credential -TenantId $tenantId
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2ecd38-7014-b642-4940-86010a7bf26a
* Version Independent ID: dca9cd31-0316-d0aa-949f-a8533c36d5cd
* Content: [Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5)
* Content Source: [docs-conceptual/partnercenterps-1.5/secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/secure-app-model.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@jonwbstr we have updated that article and release a new version. Thank you for sharing this feedback with us.
