### ISSUE TITLE
New-PartnerAccessToken

### ISSUE THREAD

**Issue by prysmcorp** [MicrosoftDocs/partner-center-docs-powershell#57]
Using the new v2.0 release of New-PartnerAccessToken and receiving the following error code back.

> New-PartnerAccessToken : AADSTS7000215: Invalid client secret is provided.

**Comment by isaiahwilliams** [comment]
@prysmcorp there was an issue which has been corrected. If you upgrade to the latest version this error will be resolved

**Comment by prysmcorp** [comment]
So I took your word in thinking that there was an issue. However, the version I'm running is already the latest. See blow.

AzureAD Module v 2.0.2.31

Partner Center Moodule
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      1909   1


I tested again today but this continues to persist.

**Comment by isaiahwilliams** [comment]
There was a new version of the Partner Center PowerShell released yesterday. It addresses this issue, the new version is 2.0.1909.2

**Comment by prysmcorp** [comment]
Terrific. I've download 2.0.1909.2 and that's now working with the exception that I'm getting the following error after the web consent:

> AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'XXXXXX-XXXXXX-XXXXXX-XXXXXX'
