### ISSUE TITLE
Consent parameter not available & Refresh Token not generated.

### ISSUE THREAD

**Issue by NasstarShannon** [MicrosoftDocs/partner-center-docs-powershell#61]
When using PartnerCentre Module v2.0.x or above the -Consent parameter is no longer available.
If omitted AccessToken can be obtained, however RefreshToken is returned as blank. 
Is anyone aware of any adjustment/change required to generate the RefreshToken?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fe2ecd38-7014-b642-4940-86010a7bf26a
* Version Independent ID: dca9cd31-0316-d0aa-949f-a8533c36d5cd
* Content: [Partner Center PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5#feedback)
* Content Source: [docs-conceptual/partnercenterps-1.5/secure-app-model.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-1.5/secure-app-model.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@NasstarShannon this article covers how to perform the secure application model using version 1.5 of the Partner Center PowerShell module. You will want to reference this [article](https://docs.microsoft.com/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0) for the new version.

**Comment by JeremyTBradshaw** [comment]
@isaiahwilliams The page that this issue was opened for has the drop down menu for version 1, 2, and 3.  All 3 versions show the same thing, including the -Consent and -Resource parameters that don't exist.  So, I think this issue was closed prematurely and the v3 version of the page should be fixed.  What do you think?
