### ISSUE TITLE
Please update this article with additional information

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/partner-center-docs-powershell#64]
1) https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0 in **Consent section** add information about the need to add http://localhost:8400 to the reply URLs of the application registration if -UseAuthorizationCode is used.

2) https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0 in **Samples Azure section** add information about -Tenant parameter - clarify that for Admin on behalf scenario (managing customer tenant) the commands to obtain $azureToken and $graphToken  have to supply customerTenantId for -Tenant paramenter, not CSP partner tenant Id ($tenantId variable)

3) https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0 in *Samples -Partner Center* clarify that correct parametrization is Connect-PartnerCenter -AccessToken $pcToken.AccessToken -Tenant $tenantId . Alternatively list which parametrizations are correct for which ParnerCenter Powershell versions

4) Consider adding "pre requisites" section to specify which powerhell version, partner center module and az modules are known to work with these commands.

**Comment by isaiahwilliams** [comment]
Thank you for providing this feedback. I have incorporated it into the upcoming update
