### ISSUE TITLE
Partner Center Powershell 1.5 - Connect-AzureRMAccount throws "Exception has been thrown by the target of an invocation"

### ISSUE THREAD

**Issue by morcinim** [MicrosoftDocs/partner-center-docs-powershell#65]
I am unable to get Partner CEnter Powershell 1.5 to work with Connect-AzureRMAccount:

1) Refresh token is captured correctly
$tenantId = 'pc_tenant_id'
$appId = 'web_app_id'
$key = 'app_secret_key'

$appSecret = ($key) | ConvertTo-SecureString -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential $appId, $appSecret

$token = New-PartnerAccessToken -Consent -Credential $credential -Resource https://api.partnercenter.microsoft.com -TenantId $tenantId 

$refreshToken=$token.RefreshToken

2) These lines execute correctly
# AzureRM Module PC Powershell 1.5 -convert refresh token to access tokens to APIs
$azureToken = New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://management.azure.com/ -Credential $credential -TenantId $customerTenantId
$graphToken =  New-PartnerAccessToken -RefreshToken $refreshToken -Resource https://graph.microsoft.com -Credential $credential -TenantId $customerTenantId

3) This line throws  throws "Exception has been thrown by the target of an invocation"
Connect-AzureRmAccount -AccessToken $azureToken.AccessToken -GraphAccessToken $graphToken.AccessToken -AccountId user@partnercenter.com-TenantId $customerTenantId

I have tested with various versions of AzureRM.profile : 4.6.0, 5.8.2, 5.8.3 but all throw same exection

**Comment by isaiahwilliams** [comment]
@morcinim there was an assembly binding redirect issue. This has been resolved with the latest release. Please let us know if there are still issues.
