### ISSUE TITLE
Get-Credential?

### ISSUE THREAD

**Issue by andyhuey** [MicrosoftDocs/partner-center-docs-powershell#66]
I'm a little confused by the use of "$credential = Get-Credential" in the examples. Wouldn't this command require credentials from an app ID and secret more like this:
"$credential = New-Object System.Management.Automation.PSCredential $appId, $appSecret" ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aefc59f-401f-2fa1-3890-579bc5fa57dd
* Version Independent ID: 7846349e-7dfe-99cd-67e5-617493f03f0a
* Content: [New-PartnerAccessToken (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partneraccesstoken?view=partnercenterps-2.0#feedback)
* Content Source: [docs/help/New-PartnerAccessToken.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/New-PartnerAccessToken.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@andyhuey using `Get-Credential` and `New-Object System.Management.Automation.PSCredential` will yield the same result. When those examples were written the decision was to use `Get-Credential` to get everything simple, but either will work.

**Comment by isaiahwilliams** [comment]
Please let us know if you have any additional questions.
