### ISSUE TITLE
Whats the available scopes?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-docs-powershell#67]
Whats the available scopes for the -Scopes parameter?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aefc59f-401f-2fa1-3890-579bc5fa57dd
* Version Independent ID: 7846349e-7dfe-99cd-67e5-617493f03f0a
* Content: [New-PartnerAccessToken (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partneraccesstoken?view=partnercenterps-2.0)
* Content Source: [docs/help/New-PartnerAccessToken.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/New-PartnerAccessToken.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@o-l-a-v there are numerous values that can be used for the `Scopes` parameter. The reason behind this is that the scopes reference the available permissions available. See [permissions and consent in the Microsoft identity platform endpoint](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent) for more information.

**Comment by isaiahwilliams** [comment]
Please let us know if you have any additional questions.
