### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by blakemartin** [MicrosoftDocs/partner-center-docs-powershell#75]
"Next it will check if the authentication method reference (ARM) claim is present. "

Should be:

 "Next it will check if the authentication method reference (AMR) claim is present."

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 757f61f0-1b20-fdc9-723a-8758e9e78626
* Version Independent ID: a00d5b47-5684-d8fd-a92f-3395989031b1
* Content: [Testing the Partner Security Requirements](https://docs.microsoft.com/en-ca/powershell/partnercenter/test-partner-security-requirements?view=partnercenterps-2.0)
* Content Source: [docs-conceptual/partnercenterps-2.0/test-partner-security-requirements.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-2.0/test-partner-security-requirements.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
Thank you for catching this. An update is being published right now and this correction has been made.
