### ISSUE TITLE
2.0 version of document does not cover how to create the application

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/partner-center-docs-powershell#77]
Hello, with the release of version 2.0 of the PartnerCenter Module, the process for creating the application has changed. Please add a section with the commands need to create the application and more importantly, set the URI correctly.

We were able to piece together a solution while working with Azure support, but a document would have been very helpful.

https://docs.microsoft.com/en-us/powershell/partnercenter/secure-app-model?view=partnercenterps-1.5

The part that caused us the most head scratching is that the redirect uri needs to use "http" and not "https".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b50142d-5f12-052b-f0df-884b98fea713
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-2.0)
* Content Source: [docs-conceptual/partnercenterps-2.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-2.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by jonwbstr** [comment]
The 1.5 version of the above document includes how to create the app, I am looking for a similar section for partner center powershell 2.0.

**Comment by isaiahwilliams** [comment]
@jonwbstr thank you for this feedback. There are a number of different ways that the Azure AD application can be created. If you are interested in using the application to connect to the Partner Center PowerShell, then the sample script available through the 1.5 documentation will work. The only difference is that you will need to include http://localhost:8400 as the redirect URI (aka reply URL) value.

Moving forward we are considering the addition of a command to the module that will generate the application. That way it is simpler for everyone to use.
