### ISSUE TITLE
Token in a AOBO scenario with AzureAD PS module - Does application have to be registered in customer tenants as well?

### ISSUE THREAD

**Issue by o-l-a-v** [MicrosoftDocs/partner-center-docs-powershell#83]
I'm trying to use Partner Center access token to authenticate against AzureAD PowerShell module.

I have a Partner Center Web Application in our partner tenant. Connecting to Partner Center with the token I get works like a charm.

* This is just the standard web application created from Partner Center web gui, no extra permissions added in Azure AD. Might be related, I was going to check this next, but the error I get does not seem to be relevant to this.

Given following code:

```powershell
# Assets
## Partner Center
$PartnerTenantId                     = '<DirectoryId>'
$PartnerTenantInitialDomain          = '<SomeDomain>.onmicrosoft.com'
$PartnerTenantAccountId              = 'some@user.com'
$PartnerTenantApplicationId          = '<ApplicationId>'
$PartnerTenantApplicationCredentials = Get-Credential -UserName $ApplicationId -Message 'Enter Application Secret.' 
## Customer
$CustomerTenantId                    = '<DirectoryId>'
$CustomerTenantInitialDomain         = '<SomeOtherDomain>onmicrosoft.com'

# Partner Center
## Get consent/ refresh token (do once)
$Token = New-PartnerAccessToken -Tenant $PartnerTenantId -ApplicationId $PartnerTenantApplicationId -ServicePrincipal -Credential $PartnerTenantApplicationCredentials -UseAuthorizationCode -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation'
$RefreshToken = $Token.'RefreshToken'
## Get access token (do every time)
$RefreshToken = Read-Host
$Token = New-PartnerAccessToken -Tenant $PartnerTenantId -ApplicationId $PartnerTenantApplicationId -RefreshToken $RefreshToken -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation'
## Connect Partner Center
Connect-PartnerCenter -Tenant $PartnerTenantId -AccessToken $Token.'AccessToken'

# Product Specific Tokens
## AzureAD Graph Token
$AadGraphToken = New-PartnerAccessToken -Tenant $CustomerTenantId -ApplicationId $PartnerTenantApplicationId -RefreshToken $RefreshToken -Credential $PartnerTenantApplicationCredentials -ServicePrincipal -Scopes 'https://graph.windows.net/.default'
## Microsoft Graph Token
$MsGraphToken  = New-PartnerAccessToken -Tenant $CustomerTenantId -ApplicationId $PartnerTenantApplicationId -RefreshToken $RefreshToken -Credential $PartnerTenantApplicationCredentials -ServicePrincipal -Scopes 'https://graph.microsoft.com/.default'
## Azure Token
$AzureToken    = New-PartnerAccessToken -Tenant $CustomerTenantId -ApplicationId $PartnerTenantApplicationId -RefreshToken $RefreshToken -Credential $PartnerTenantApplicationCredentials -ServicePrincipal -Scopes 'https://management.azure.com//user_impersonation'
```

I get following error for all of the "#Product Specific Tokens" lines:

```
New-PartnerAccessToken : AADSTS700016: Application with identifier '<secret>' was not found in the directory <secret>'. This can happen 
if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
Trace ID: <secret>;
Correlation ID: <secret>;
Timestamp: 2019-12-10 12:18:18Z
At line:6 char:18
+ ... eToken    = New-PartnerAccessToken -Tenant $CustomerTenantId -Applica ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-PartnerAccessToken], MsalServiceException
    + FullyQualifiedErrorId : Microsoft.Store.PartnerCenter.PowerShell.Commands.NewPartnerAccessToken
```

Question time:

* Does the app have to be registered inside each and every customer tenant as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958c342f-ff57-a57b-9426-8b1bbc9460b2
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0)
* Content Source: [docs-conceptual/partnercenterps-3.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by o-l-a-v** [comment]
So I tried creating a AAD Application using [Isiah Wiliams suggested PowerShell code](https://www.microsoftpartnercommunity.com/t5/Secure-Application-Model/Connect-AzureAD-to-Other-Tenants-with-Secure-Application-Model/m-p/14775/highlight/true#M116) which creates a App Registration with Web redirect uri "urn:ietf:wg:oauth:2.0:oob".

I then tried to use that for getting refresh token with Partner Center module 3.0, but the login windows that pops up in browser says "AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: '794b7b12-2829-48c5-8f15-633d8f530d18'."

Tried both of the following methods

```powershell
### Web App (RedirectUri is of type "Web")
$Token = New-PartnerAccessToken -Tenant $PartnerTenantId -ApplicationId $PartnerTenantApplicationId -ServicePrincipal -Credential $PartnerTenantApplicationCredentials -UseAuthorizationCode -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation'
### Native App (RedirectUri is not of type "Web")
$Token = New-PartnerAccessToken -Tenant $PartnerTenantId -ApplicationId $PartnerTenantApplicationId -UseAuthorizationCode -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation'
```

Am I goofing? I can't remember to have seen App Registrations of type "Web" with redirecturi "urn:ietf:wg:oauth:2.0:oob", in fact you can't even put that into Azure Portal GUI.

![image](https://user-images.githubusercontent.com/6450056/70533071-8fb07680-1b58-11ea-914a-3bfa831c6c1d.png)

<details><summary>Modules info</summary><p>

```powershell

Name                                   Version         
----                                   -------         
AzureAD                                2.0.2.76        
ISE                                    1.0.0.0         
Microsoft.Graph.Intune                 6.1907.1.0      
Microsoft.Online.SharePoint.PowerShell 16.0.19515.12000
Microsoft.PowerShell.Management        3.1.0.0         
Microsoft.PowerShell.Security          3.0.0.0         
Microsoft.PowerShell.Utility           3.1.0.0         
Microsoft.WSMan.Management             3.0.0.0         
PackageManagement                      1.4.5           
PartnerCenter                          3.0.0           
PowerShellGet                          2.2.1           
```

</p></details>

**Comment by isaiahwilliams** [comment]
@o-l-a-v with the release of version 2.0 and later the process has changed slightly. Since you are using version 3.0 you will need to specify http://localhost:8400 as the redirect URI. You can find more information [here](https://docs.microsoft.com/en-us/powershell/module/partnercenter/new-partneraccesstoken?view=partnercenterps-3.0)

**Comment by rphoon** [comment]
I'm having a similar issue. I am running the exact same commands but when I run "$AzureToken = New-PartnerAccessToken -Tenant $CustomerTenantId -ApplicationId $PartnerTenantApplicationId -RefreshToken $RefreshToken -Credential $PartnerTenantApplicationCredentials -ServicePrincipal -Scopes 'https://management.azure.com/user_impersonation'", I get the following error:

New-PartnerAccessToken : AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'xxxx'
