### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ollliegits** [MicrosoftDocs/partner-center-docs-powershell#85]
There found a typo its way into this page:

Under 'Provide feedback':
https://github.com/microsoft/partner-center-powersehll/issues

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a17241e-513a-3438-b782-be5a7fa53a05
* Version Independent ID: 0cb11757-bbee-e154-18f4-d36cf0b47a5d
* Content: [Install Partner Center PowerShell with PowerShellGet](https://docs.microsoft.com/en-us/powershell/partnercenter/install?view=partnercenterps-3.0#feedback)
* Content Source: [docs-conceptual/partnercenterps-3.0/install.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/install.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@ollliegits thank you for bringing this to my attention. An update that corrects this is being deployed right now.
