### ISSUE TITLE
Is this the same as clicking the "Transition billing to Azure plan" button in the PartnerCenter?

### ISSUE THREAD

**Issue by ssugar** [MicrosoftDocs/partner-center-docs-powershell#94]
Looking for the powershell equivalent of the "Transition billing to Azure plan" button in the PartnerCenter web portal.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27778481-2542-f895-2882-581a9522b159
* Version Independent ID: 1945aea8-717b-3a37-c863-8485cb322243
* Content: [New-PartnerProductUpgrade (PartnerCenter)](https://docs.microsoft.com/en-us/powershell/module/partnercenter/New-PartnerProductUpgrade?view=partnercenterps-3.0#feedback)
* Content Source: [docs/help/New-PartnerProductUpgrade.md](https://github.com/Microsoft/Partner-Center-PowerShell/blob/master/docs/help/New-PartnerProductUpgrade.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@ssugar almost when you click that in Partner Center it is actually doing two operations. The first is where an eligibility check is done to ensure that the upgrade can happen. You can perform this by running the [Get-PartnerProductUpgradeEligibility](https://docs.microsoft.com/powershell/module/partnercenter/get-partnerproductupgradeeligibility) command. If that does not return any issues, then you can start the upgrade with this command.

**Comment by ssugar** [comment]
perfect, thanks @isaiahwilliams
