### ISSUE TITLE
PartnerCenter Powershell Example

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/partner-center-docs-powershell#95]
Hello,
I also notice the Partner Center example is setting $credential, and then not using the variable. Either the varible does not need to be set, or the connect-partnercenter command should include the variable that was set.

Example: "Connect-PartnerCenter -ApplicationId 'xxxx-xxxx-xxxx-xxxx' -RefreshToken $refreshToken"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 958c342f-ff57-a57b-9426-8b1bbc9460b2
* Version Independent ID: 91e502bc-30e1-c879-7b51-22399f6988f5
* Content: [Automating tasks with PowerShell](https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0)
* Content Source: [docs-conceptual/partnercenterps-3.0/multi-factor-auth.md](https://github.com/MicrosoftDocs/partner-center-docs-powershell/blob/live/docs-conceptual/partnercenterps-3.0/multi-factor-auth.md)
* Product: **partner-center**
* GitHub Login: @isaiahwilliams
* Microsoft Alias: **iswillia**

**Comment by isaiahwilliams** [comment]
@jonwbstr I have updated the article to use the variable and explain why it might be required. If you are using a confidential client (known as a web application in Azure AD), then the application identifier and secret are required values for each authentication request. This includes the exchange of a refresh token for an access token. If you are using a public client (known as a public client with Azure AD), then this value is not required.
